#!/bin/bash

. /opt/helpers

sed -i "s/80/$APACHE_HTTP_PORT/g" /etc/apache2/ports.conf /etc/apache2/sites-available/*
sed -i "s/443/$APACHE_HTTPS_PORT/g" /etc/apache2/ports.conf /etc/apache2/sites-available/*

service apache2 start

# Allow any signal which would kill a process to stop server
trap "service apache2 stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u www-data apache2 > /dev/null; do sleep 5; done
